CREATE DATABASE music_db;

USE music_db;

CREATE TABLE Artist (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Album (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    ArtistId INT,
    FOREIGN KEY (ArtistId) REFERENCES Artist(Id)
);

CREATE TABLE Track (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Time INT(3) NOT NULL,
    AlbumId INT,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id)
);